### ISSUE TITLE
Why do you choose this kind of GRU variants, instead of LSTM?

### ISSUE THREAD

**Issue by speedcell4** [Adaxry/GCDT#3]
Hi~

I tried a similar architecture, with all your GRU variants replaced with standard LSTMs/BiLSTM, and it reached 91.96 (compared with your model in Figure 1, w/o BERT) on CoNLL 2003 NER task.

Yes, I know you mentioned this kind of thing in Section 1, 
> While in BiLSTMs, even stacked BiLSTMs, the transition depth between consecutive hidden states are inherently shallow

But I don't know what do you mean by **transition depth** and how do you measure it? Could you give me more details about this? And have you tried LSTM before? If yes, could you please show me your experimental results? If no, could you explain why you need to design this kind of GRU variants?

Thanks~

**Comment by Adaxry** [comment]
- How to understand **transition depth**?
The **transition depth** is the depth of the hidden-to-hidden transition between the consecutive hidden states in RNN, and more details are suggested to refer this paper "How to Construct Deep Recurrent Neural Networks". (ICLR-2014) 

- Compared with stacked RNN
The DT-RNN and stacked-RNN extend the conventional RNN in different aspects, and are orthogonal.

- Why only use DT-GRU instead of DT-LSTM?
This deep transition architecture is easily extended to both GRU and LSTM. No significant differences are observed in our preliminary experiments, so we simply choose this GRU variants.

**Comment by speedcell4** [comment]
Thank you
